spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch_mysql
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      enabled: true
      name: importJob
    jdbc:
      initialize-schema: never
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org.springframework.batch: debug
